name: Build, push and deploy Docker image

on:
  push:
    # only run if pushing tags
    branches:
    - refs/tags/*

# Enables BuildKit
env:
  DOCKER_IMAGE_ORG: ghcr.io/workadventure-suse
  DOCKER_IMAGE_REPOSITORY: workadventure

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Create a slugified value of the branch
      - uses: rlespinasse/github-slug-action@3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: "Build and push front image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: front/Dockerfile
          push: true
          tags: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-front:${{ env.GITHUB_REF_SLUG }}"
          labels: "org.opencontainers.image.source=https://github.com/workadventure-suse/workadventure/front"

      - name: "Build and push back image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: back/Dockerfile
          push: true
          tags: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-back:${{ env.GITHUB_REF_SLUG }}"
          labels: "org.opencontainers.image.source=https://github.com/workadventure-suse/workadventure/back"

      - name: "Build and push pusher image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: pusher/Dockerfile
          push: true
          tags: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-pusher:${{ env.GITHUB_REF_SLUG }}"
          labels: "org.opencontainers.image.source=https://github.com/workadventure-suse/workadventure/pusher"

      - name: "Build and push uploader image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: uploader/Dockerfile
          push: true
          tags: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-uploader:${{ env.GITHUB_REF_SLUG }}"
          labels: "org.opencontainers.image.source=https://github.com/workadventure-suse/workadventure/uploader"
  # build-back:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Create a slugified value of the branch
  #     - uses: rlespinasse/github-slug-action@3.1.0

  #     - name: "Build and push back image"
  #       uses: docker/build-push-action@v1
  #       with:
  #         dockerfile: back/Dockerfile
  #         path: ./
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.CR_PAT }}
  #         repository: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-back"
  #         tags: ${{ env.GITHUB_REF_SLUG }}
  #         add_git_labels: true

  # build-pusher:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Create a slugified value of the branch
  #     - uses: rlespinasse/github-slug-action@3.1.0

  #     - name: "Build and push back image"
  #       uses: docker/build-push-action@v1
  #       with:
  #         dockerfile: pusher/Dockerfile
  #         path: ./
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.CR_PAT }}
  #         repository: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-pusher"
  #         tags: ${{ env.GITHUB_REF_SLUG }}
  #         add_git_labels: true

  # build-uploader:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Create a slugified value of the branch
  #     - uses: rlespinasse/github-slug-action@3.1.0

  #     - name: "Build and push back image"
  #       uses: docker/build-push-action@v1
  #       with:
  #         dockerfile: uploader/Dockerfile
  #         path: ./
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.CR_PAT }}
  #         repository: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-uploader"
  #         tags: ${{ env.GITHUB_REF_SLUG }}
  #         add_git_labels: true

  # # build-maps:
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #     - name: Checkout
  # #       uses: actions/checkout@v2


  # #     # Create a slugified value of the branch
  # #     - uses: rlespinasse/github-slug-action@3.1.0

  # #     - name: "Build and push front image"
  # #       uses: docker/build-push-action@v1
  # #       with:
  # #         dockerfile: maps/Dockerfile
  # #         path: maps/
  # #         username: ${{ secrets.DOCKER_USERNAME }}
  # #         password: ${{ secrets.DOCKER_PASSWORD }}
  # #         repository: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPOSITORY}}-maps"
  # #         tags: ${{ env.GITHUB_REF_SLUG }}
  # #         add_git_labels: true
